# Generated by Django 4.2.6 on 2024-02-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Completed', 'Complete'), ('Pending', 'Pending')], max_length=50),
        ),
    ]
